version: "2.1"

volumes:
  home-assistant-config:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
  otbr-data:
  matter-data:

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.1.0
    network_mode: host
    privileged: true
    mem_limit: 500m
    mem_reservation: 450m
    memswap_limit: 612m
    labels:
      io.balena.features.dbus: "1"
    volumes:
      - home-assistant-config:/config
    environment:
      - TZ=Europe/Athens # Set your timezone here instead of mounting /etc/localtime
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Zigbee stick
      # - /dev/ttyUSB1:/dev/ttyUSB1 # Thread/Matter stick - Handled in otbr
      - /dev/ttyAMA0:/dev/ttyAMA0 # Add this for Bluetooth
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN # Add this for Bluetooth access
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    network_mode: host
    mem_limit: 100m
    mem_reservation: 50m
    memswap_limit: 200m
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  otbr:
    image: openthread/border-router:latest
    container_name: otbr
    network_mode: host
    privileged: true
    # mem_limit: 100m
    # mem_reservation: 50m
    # memswap_limit: 200m
    ports:
      - "8981:8981"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN # Add this for Bluetooth access
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/net/tun:/dev/net/tun
    environment:
      OT_RCP_DEVICE: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800
      OT_INFRA_IF: eth0
      OT_THREAD_IF: wpan0
      OT_LOG_LEVEL: 7
      OTBR_WEB_PORT: 8981
      OT_REST_LISTEN_PORT: 8981
      OT_REST_PORT: 8981
    volumes:
      - otbr-data:/data

  # Will be replaced with https://github.com/matter-js/matterjs-server/blob/a44245e65c619479182530635ce0863dbdae605f/docker/matterjs-server/docker-compose.yml
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    network_mode: host
    mem_limit: 100m
    mem_reservation: 50m
    memswap_limit: 200m
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - matter-data:/data
    devices:
      - /dev/hci0:/dev/hci0 # if you use Bluetooth on the host; optional
    command: >
      --storage-path /data
      --paa-root-cert-dir /data/credentials
      --bluetooth-adapter 0
